### ISSUE TITLE
프로젝트 폴더 구조 설정

### ISSUE THREAD

**Issue by JangWooJin1** [Pda5th-SolZipMoa/front#1]
## Description

- 기본 프로젝트 폴더 구조 및 라우팅 설정 작업.

## Todo

- [x] 브라우저 탭 타이틀 및 아이콘 커스터마이징
- [x] React Router 설치 및 기본 설정 적용
- [x] 기본 폴더 구조 생성 (`components`, `pages`, `routers`)
- [x] 라우팅 설정 파일 `AppRouter.jsx` 생성 및 초기 라우팅 구성
