### ISSUE TITLE
페이지 라우팅 연결 

### ISSUE THREAD

**Issue by yy2013396** [Pda5th-SolZipMoa/front#12]
## Description
- 제작된 페이지 간 라우팅과 함께 데이터를 연결합니다. 

## Todo

- [ ] 홈 페이지에서 건물 상세 페이지로의 라우팅, 데이터 전달 
- [ ] 홈 페이지에서 토큰 발행 페이지로의 라우팅, 데이터 전달
- [ ] 건물 상세 페이지에서 거래 페이지로 라우팅
