### ISSUE TITLE
토큰 발행 페이지 디테일 분류

### ISSUE THREAD

**Issue by besthong** [Pda5th-SolZipMoa/front#24]
## Description

- 토큰 발행 페이지 내 건물명,주소 외 층수,방 개수, 집 평수, 유지비 추가

## Todo

- [x] 층수 구현
- [x] 방 개수 구현
- [x] 집 평수 구현
- [x] 유지비 구현
- [x] 메인 건물사진, 집 사진 분류 
- [x] 디자인 구현
- [x] 건물 정보 페이지 연결
- [x] 토큰 생성 페이지 연결
