### ISSUE TITLE
마이페이지 구현

### ISSUE THREAD

**Issue by JangWooJin1** [Pda5th-SolZipMoa/front#29]
## Description

- 마이페이지에서 사용자 보유 자산, 거래 내역, 미체결 주문 내역을 확인하고 관리할 수 있도록 구현
- API와 연동하여 데이터를 표시하고, 사용자가 미체결 주문을 취소할 수 있는 기능 추가

## Todo

- 보유 자산 섹션 구현
  - [x] 포트폴리오: 파이차트로 사용자 보유 종목의 비율을 시각화
  - [x] 내 자산: 보유 자산, 평가 금액, 손익 등을 확인할 수 있는 UI 구현
  - [x] 보유 종목: 사용자가 소유한 종목의 상세 정보를 리스트로 확인 가능
- 거래 내역 섹션 구현
  - [x] 체결 내역: 사용자의 체결된 주문 기록을 표시
  - [x] 취소 내역: 취소된 주문 기록을 표시
- 미체결 주문 내역 섹션 구현
  - [x] 미체결 주문 목록 확인 UI 구현
  - [x] 미체결 주문 취소 기능 추가
