### ISSUE TITLE
메인 페이지 구현

### ISSUE THREAD

**Issue by yy2013396** [Pda5th-SolZipMoa/front#3]
## Description

- 카카오 지도 렌더링 및 SOL 매물 리스트 UI 작업  

## Todo

- [x] 공통 헤더 구현
- [x] 카카오 지도 API 연동 및 렌더링 
- [x] 지도 검색 기능 구현
- [x] SOL 매물 데이터를 기반으로 지도에 위치 표시
- [x] 매물 리스트 구현, 매물 클릭 시 지도와 연동
- [x] 매물 리스트 정렬 필터
