### ISSUE TITLE
토큰 거래 페이지 리펙토링

### ISSUE THREAD

**Issue by JangWooJin1** [Pda5th-SolZipMoa/front#45]
## Description

1. **주문 수량 제한**: 매수/매도 주문 제출 시 수량이 1,000원 단위가 아닐 경우, 제출되지 않도록 제한
2. **기본 가격 설정**: 주문 창을 열었을 때, 가격 입력란에 최신 시장 가격이 기본값으로 설정

## Todo

- [x] 매수/매도 주문 시 수량이 1,000원 단위인지 검증하는 로직 구현
- [x] 수량 조건을 만족하지 않을 경우 제출 버튼 비활성화 또는 에러 메시지 표시
- [x] 주문 창 열 때 최신 시장 가격을 동적으로 불러오는 기능 구현
- [x] 가격 입력란에 최신 시장 가격을 기본값으로 설정
