### ISSUE TITLE
전체적인 디자인 수정

### ISSUE THREAD

**Issue by JangWooJin1** [Pda5th-SolZipMoa/front#48]
## Description

- 상단 헤더 스타일 수정, 메인 페이지 디자인 수정, 토큰 발행 페이지 디자인 수정, 마이 페이지 디자인 수정, 건물 상세 페이지 디자인 수정 작업을 진행

## Todo

- [x] 상단 헤더 스타일 수정
- [x] 메인 페이지 디자인 수정
- [x] 토큰 발행 페이지 디자인 수정
- [x] 마이 페이지 디자인 수정
- [x] 건물 상세 페이지 디자인 수정
- [x] 토큰 거래 페이지 디자인 수정
