### ISSUE TITLE
청약 페이지의 기능을 구현하겠습니다.

### ISSUE THREAD

**Issue by yy2013396** [Pda5th-SolZipMoa/front#50]
## Description

- 청약 관련 데이터 표시
- 사용자에게 제공되는 청약 상품 목록을 카드 형식 또는 테이블로 표시.

## Todo

- [x] 청약 상품에 청약할 수 있는 기능 
- [x] 청약 진행 상황 게이지화 
- [x] 마이페이지 내에서 청약 토큰 거래 상황을 조회할 수 있도록 구현
