### ISSUE TITLE
건물 상세페이지 구현

### ISSUE THREAD

**Issue by besthong** [Pda5th-SolZipMoa/front#7]
## Description

- 건물 상세페이지 구현

## Todo

- [x] 프론트 화면 구성
- [x] 건물 정보 api 연동
- [x] 시세 정보 api 연동
- [x] 지도 api 연동
- [x] 메인 이미지,썸네일 연동
